#!/usr/bin/env python3
"""Auto-generate DuckStation Lua logger scripts from address JSON files.

Reads address definitions from addresses/{game_id}.json (managed by
address_manager.py) and generates a ready-to-use Lua script that logs
those memory addresses to CSV.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from address_manager import AddressManager

# Mapping from our data types to DuckStation Lua Memory API functions
TYPE_MAP = {
    "int8": ("byte", "Memory.ReadByte"),
    "uint8": ("byte", "Memory.ReadByte"),
    "int16": ("word", "Memory.ReadWord"),
    "uint16": ("word", "Memory.ReadWord"),
    "int32": ("dword", "Memory.ReadDWord"),
    "uint32": ("dword", "Memory.ReadDWord"),
    "float32": ("dword", "Memory.ReadDWord"),  # raw read, needs reinterpret
}


def generate_lua_script(
    game_id: str,
    addresses_dir: Path | None = None,
    log_interval: int = 300,
) -> str:
    """Generate a DuckStation Lua logger script for the given game.

    Args:
        game_id: Game identifier (must have addresses/{game_id}.json).
        addresses_dir: Directory containing address JSON files.
        log_interval: Frames between log entries (300 = 5s at 60fps).

    Returns:
        Lua script as a string.
    """
    manager = AddressManager(
        addresses_dir or Path.home() / "ps1-ai-player" / "addresses"
    )
    game_addrs = manager.load(game_id)

    if not game_addrs.parameters:
        raise ValueError(
            f"No addresses found for game '{game_id}'. "
            f"Use address_manager.py to add parameters first."
        )

    # Build the address table entries
    addr_entries = []
    for name, info in game_addrs.parameters.items():
        addr_int = int(info.address, 16)
        lua_type, lua_func = TYPE_MAP.get(info.type, ("dword", "Memory.ReadDWord"))
        addr_entries.append(
            f'    {{ name = "{name}", '
            f'address = 0x{addr_int:08X}, '
            f'type = "{lua_type}", '
            f'reader = "{lua_func}" }},'
        )

    addr_table = "\n".join(addr_entries)
    param_count = len(game_addrs.parameters)

    script = f"""\
-- DuckStation Lua Script: Memory Logger for {game_id}
-- Auto-generated by lua_generator.py
-- Tracks {param_count} parameters from addresses/{game_id}.json
--
-- Usage: Place in DuckStation scripts directory or load manually.

-- Configuration
local LOG_INTERVAL = {log_interval}  -- Frames between log entries
local LOG_DIR = os.getenv("HOME") .. "/ps1-ai-player/logs/"
local GAME_ID = "{game_id}"

-- Address definitions (auto-generated from JSON)
local addresses = {{
{addr_table}
}}

-- Internal state
local frame_count = 0
local log_file = nil
local log_path = ""

--- Read a memory value based on type string.
local function read_typed(addr, dtype)
    if dtype == "byte" then
        return Memory.ReadByte(addr)
    elseif dtype == "word" then
        return Memory.ReadWord(addr)
    elseif dtype == "dword" then
        return Memory.ReadDWord(addr)
    else
        Console.WriteLn("[Logger] Unknown type: " .. dtype)
        return 0
    end
end

--- Generate the CSV header line.
local function make_header()
    local parts = {{ "frame" }}
    for _, entry in ipairs(addresses) do
        table.insert(parts, entry.name)
    end
    return table.concat(parts, ",")
end

--- Read all addresses and format as a CSV line.
local function make_row()
    local parts = {{ tostring(frame_count) }}
    for _, entry in ipairs(addresses) do
        local val = read_typed(entry.address, entry.type)
        table.insert(parts, tostring(val))
    end
    return table.concat(parts, ",")
end

--- Initialize the log file.
local function init_log()
    local timestamp = os.date("%Y%m%d_%H%M%S")
    log_path = LOG_DIR .. timestamp .. "_" .. GAME_ID .. "_lua.csv"

    log_file = io.open(log_path, "w")
    if log_file then
        log_file:write(make_header() .. "\\n")
        log_file:flush()
        Console.WriteLn("[Logger] Logging to: " .. log_path)
    else
        Console.WriteLn("[Logger] ERROR: Could not open log file: " .. log_path)
    end
end

--- Write a log entry if the interval has elapsed.
local function update_log()
    if log_file == nil then
        return
    end

    if frame_count % LOG_INTERVAL == 0 then
        local row = make_row()
        log_file:write(row .. "\\n")
        log_file:flush()

        if frame_count % (LOG_INTERVAL * 12) == 0 then
            Console.WriteLn("[Logger] Frame " .. frame_count .. ": " .. row)
        end
    end
end

--- Close the log file cleanly.
local function close_log()
    if log_file then
        log_file:close()
        log_file = nil
        Console.WriteLn("[Logger] Log saved to: " .. log_path)
    end
end

-- DuckStation Callbacks

function OnScriptLoaded()
    Console.WriteLn("[Logger] {game_id} logger loaded")
    Console.WriteLn("[Logger] Tracking " .. #addresses .. " parameters")
    Console.WriteLn("[Logger] Log interval: " .. LOG_INTERVAL .. " frames")
    os.execute("mkdir -p " .. LOG_DIR)
    init_log()
end

function UpdatePerFrame()
    frame_count = frame_count + 1
    update_log()
end

function OnScriptUnloaded()
    close_log()
    Console.WriteLn("[Logger] Logger unloaded")
end
"""
    return script


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate DuckStation Lua logger from address JSON"
    )
    parser.add_argument(
        "--game", "-g", required=True, help="Game ID (must have addresses JSON)"
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Output Lua file path (default: lua_loggers/{game_id}.lua)",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=300,
        help="Log interval in frames (default: 300 = 5s at 60fps)",
    )
    parser.add_argument(
        "--addresses-dir",
        type=Path,
        default=None,
        help="Address JSON directory",
    )

    args = parser.parse_args()

    script = generate_lua_script(
        game_id=args.game,
        addresses_dir=args.addresses_dir,
        log_interval=args.interval,
    )

    if args.output:
        output_path = args.output
    else:
        output_dir = Path.home() / "ps1-ai-player" / "lua_loggers"
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{args.game}.lua"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(script)
    print(f"Generated Lua logger: {output_path}")


if __name__ == "__main__":
    main()
