#!/usr/bin/env python3
"""Real-time memory parameter watcher with threshold alerts and spike detection.

Extends the monitoring capabilities of memory_logger.py by adding:
  - User-defined threshold rules (lt/gt/le/ge) with configurable severity
  - Streaming spike detection using sliding-window z-score (from anomaly_detector logic)
  - Alert accumulation and SSE-compatible event generation
  - Strategy config interop (from_strategy_config classmethod)

Usage:
    python memory_watcher.py check <session_csv> [--rules rules.json] [--strategy config.json]
    python memory_watcher.py check <session_csv> --spike-threshold 3.0
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from log_config import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class ThresholdRule:
    """A single parameter threshold rule for alerting."""

    parameter: str
    operator: str  # "lt", "gt", "le", "ge"
    value: float
    severity: str = "medium"  # "low", "medium", "high"
    message: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "parameter": self.parameter,
            "operator": self.operator,
            "value": self.value,
            "severity": self.severity,
            "message": self.message,
        }


@dataclass
class WatcherAlert:
    """A single alert generated by the watcher."""

    kind: str  # "threshold", "spike"
    severity: str  # "low", "medium", "high"
    parameter: str
    value: float
    description: str
    timestamp: str
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "severity": self.severity,
            "parameter": self.parameter,
            "value": self.value,
            "description": self.description,
            "timestamp": self.timestamp,
            "details": self.details,
        }


# ---------------------------------------------------------------------------
# MemoryWatcher
# ---------------------------------------------------------------------------

_OPERATORS = {
    "lt": lambda v, t: v < t,
    "gt": lambda v, t: v > t,
    "le": lambda v, t: v <= t,
    "ge": lambda v, t: v >= t,
}


class MemoryWatcher:
    """Real-time parameter watcher with threshold alerts and spike detection.

    Feed parameter values via :meth:`check_value` or :meth:`check_values`
    to accumulate alerts.  Alerts are stored internally and can be retrieved
    via :attr:`alerts`, :meth:`alert_summary`, :meth:`to_dict`, or
    :meth:`to_markdown`.
    """

    def __init__(
        self,
        rules: list[ThresholdRule | dict],
        *,
        spike_threshold: float = 2.5,
        window_size: int = 20,
    ) -> None:
        self.rules: list[ThresholdRule] = []
        for r in rules:
            if isinstance(r, dict):
                self.rules.append(ThresholdRule(**r))
            else:
                self.rules.append(r)

        self.spike_threshold = spike_threshold
        self.window_size = window_size

        # Sliding windows for spike detection (parameter -> list of values)
        self._windows: dict[str, list[float]] = {}

        # Accumulated alerts
        self._alerts: list[WatcherAlert] = []

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def from_strategy_config(
        cls,
        config: dict[str, Any],
        **kwargs: Any,
    ) -> MemoryWatcher:
        """Create a MemoryWatcher from a strategy config JSON.

        Strategy thresholds (same format as ``config/strategies/*.json``)
        are converted to :class:`ThresholdRule` instances.  The threshold
        ``priority`` is mapped to severity: >=8 → high, >=5 → medium,
        else → low.
        """
        rules: list[ThresholdRule] = []
        for t in config.get("thresholds", []):
            priority = t.get("priority", 5)
            if priority >= 8:
                severity = "high"
            elif priority >= 5:
                severity = "medium"
            else:
                severity = "low"
            target = t.get("target_strategy", "alert")
            rules.append(ThresholdRule(
                parameter=t["parameter"],
                operator=t["operator"],
                value=t["value"],
                severity=severity,
                message=f"{t['parameter']} {t['operator']} {t['value']} -> {target}",
            ))
        return cls(rules, **kwargs)

    # ------------------------------------------------------------------
    # Checking
    # ------------------------------------------------------------------

    def check_value(
        self,
        parameter: str,
        value: float,
        timestamp: str = "",
    ) -> list[WatcherAlert]:
        """Check a single parameter value against rules and spike detection.

        Returns new alerts generated by this check (also stored internally).
        """
        ts = timestamp or datetime.now().isoformat()
        new_alerts: list[WatcherAlert] = []

        # 1. Threshold checks
        for rule in self.rules:
            if rule.parameter != parameter:
                continue
            op_fn = _OPERATORS.get(rule.operator)
            if op_fn is None:
                continue
            if op_fn(value, rule.value):
                msg = rule.message or f"{parameter} {rule.operator} {rule.value}"
                new_alerts.append(WatcherAlert(
                    kind="threshold",
                    severity=rule.severity,
                    parameter=parameter,
                    value=value,
                    description=f"Threshold alert: {msg} (current: {value})",
                    timestamp=ts,
                    details={
                        "rule_operator": rule.operator,
                        "rule_value": rule.value,
                    },
                ))

        # 2. Spike detection (sliding window z-score on deltas)
        window = self._windows.setdefault(parameter, [])
        window.append(value)
        if len(window) > self.window_size:
            window[:] = window[-self.window_size:]

        if len(window) >= 3:
            deltas = [window[i] - window[i - 1] for i in range(1, len(window))]
            if len(deltas) >= 2:
                mean_d = statistics.mean(deltas)
                std_d = statistics.stdev(deltas)
                if std_d > 0:
                    latest_delta = deltas[-1]
                    z = abs(latest_delta - mean_d) / std_d
                    if z >= self.spike_threshold:
                        severity = (
                            "high" if z >= 4.0
                            else "medium" if z >= 3.0
                            else "low"
                        )
                        new_alerts.append(WatcherAlert(
                            kind="spike",
                            severity=severity,
                            parameter=parameter,
                            value=value,
                            description=(
                                f"Spike in {parameter}: "
                                f"delta={latest_delta:.2f} (z={z:.2f})"
                            ),
                            timestamp=ts,
                            details={
                                "delta": round(latest_delta, 4),
                                "z_score": round(z, 4),
                                "mean_delta": round(mean_d, 4),
                                "std_delta": round(std_d, 4),
                            },
                        ))

        self._alerts.extend(new_alerts)
        return new_alerts

    def check_values(
        self,
        values: dict[str, float],
        timestamp: str = "",
    ) -> list[WatcherAlert]:
        """Check multiple parameter values at once.

        Returns all new alerts generated.
        """
        new_alerts: list[WatcherAlert] = []
        for param, val in values.items():
            new_alerts.extend(self.check_value(param, val, timestamp))
        return new_alerts

    # ------------------------------------------------------------------
    # Alert access
    # ------------------------------------------------------------------

    @property
    def alerts(self) -> list[WatcherAlert]:
        """All accumulated alerts (oldest first)."""
        return list(self._alerts)

    def clear_alerts(self) -> None:
        """Clear all accumulated alerts."""
        self._alerts.clear()

    def alert_summary(self) -> dict[str, Any]:
        """Summary statistics of accumulated alerts."""
        by_kind: dict[str, int] = {}
        by_severity: dict[str, int] = {}
        by_parameter: dict[str, int] = {}
        for a in self._alerts:
            by_kind[a.kind] = by_kind.get(a.kind, 0) + 1
            by_severity[a.severity] = by_severity.get(a.severity, 0) + 1
            by_parameter[a.parameter] = by_parameter.get(a.parameter, 0) + 1

        return {
            "total": len(self._alerts),
            "by_kind": by_kind,
            "by_severity": by_severity,
            "by_parameter": by_parameter,
        }

    # ------------------------------------------------------------------
    # Output
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """JSON-serialisable dict of watcher state and alerts."""
        return {
            "rules": [r.to_dict() for r in self.rules],
            "spike_threshold": self.spike_threshold,
            "window_size": self.window_size,
            "summary": self.alert_summary(),
            "alerts": [a.to_dict() for a in self._alerts],
        }

    def to_markdown(self) -> str:
        """Alert report in Markdown format."""
        lines: list[str] = [
            "# Memory Watcher Report",
            "",
            f"Rules configured: {len(self.rules)}",
            f"Spike threshold: {self.spike_threshold}",
            f"Total alerts: {len(self._alerts)}",
            "",
        ]

        if not self._alerts:
            lines.append("No alerts triggered.")
            return "\n".join(lines)

        # Group by kind
        thresholds = [a for a in self._alerts if a.kind == "threshold"]
        spikes = [a for a in self._alerts if a.kind == "spike"]

        severity_label = {"high": "[HIGH]", "medium": "[MED]", "low": "[LOW]"}

        if thresholds:
            lines.append("## Threshold Alerts")
            lines.append("")
            for a in thresholds:
                label = severity_label.get(a.severity, "[?]")
                lines.append(f"- {label} {a.description}")
            lines.append("")

        if spikes:
            lines.append("## Spike Alerts")
            lines.append("")
            for a in spikes:
                label = severity_label.get(a.severity, "[?]")
                lines.append(f"- {label} {a.description}")
            lines.append("")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="memory_watcher",
        description="Real-time parameter watcher with threshold alerts and spike detection.",
    )
    sub = parser.add_subparsers(dest="command")

    p_check = sub.add_parser("check", help="Check a session CSV against threshold rules")
    p_check.add_argument("session_csv", help="Path to session CSV file")
    p_check.add_argument(
        "--rules", default=None,
        help="JSON file with threshold rules (list of {parameter, operator, value, severity, message})",
    )
    p_check.add_argument(
        "--strategy", default=None,
        help="Strategy config JSON file (same format as config/strategies/*.json)",
    )
    p_check.add_argument(
        "--spike-threshold", type=float, default=2.5,
        help="Z-score threshold for spike detection (default: 2.5)",
    )
    p_check.add_argument(
        "--format", choices=["markdown", "json"], default="markdown",
        help="Output format (default: markdown)",
    )
    p_check.add_argument(
        "--output", default=None,
        help="Write report to file (default: stdout)",
    )

    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        sys.exit(1)

    import pandas as pd
    from session_replay import _FIXED_COLUMNS

    csv_path = Path(args.session_csv)
    if not csv_path.exists():
        print(f"Session CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    df = pd.read_csv(csv_path)
    parameters = [
        c for c in df.columns
        if c not in _FIXED_COLUMNS and pd.api.types.is_numeric_dtype(df[c])
    ]

    if not parameters:
        print("No numeric parameters found in CSV.")
        return

    # Load rules
    rules: list[ThresholdRule] = []
    if args.strategy:
        config = json.loads(Path(args.strategy).read_text())
        watcher = MemoryWatcher.from_strategy_config(
            config, spike_threshold=args.spike_threshold,
        )
    elif args.rules:
        raw_rules = json.loads(Path(args.rules).read_text())
        watcher = MemoryWatcher(
            raw_rules, spike_threshold=args.spike_threshold,
        )
    else:
        # No rules — spike detection only
        watcher = MemoryWatcher([], spike_threshold=args.spike_threshold)

    # Feed all rows
    for _, row in df.iterrows():
        values = {}
        for param in parameters:
            try:
                values[param] = float(row[param])
            except (ValueError, TypeError):
                pass
        ts = str(row.get("timestamp", ""))
        watcher.check_values(values, ts)

    if args.format == "json":
        output = json.dumps(watcher.to_dict(), indent=2, default=str)
    else:
        output = watcher.to_markdown()

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output)
        logger.info("Report written to %s", out_path)
    else:
        print(output)


if __name__ == "__main__":
    main()
